name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      # Restore dependencies for the entire solution.
      run: dotnet restore Cloudflare.NET.sln

    - name: Build solution
      # Build the entire solution to ensure all projects compile.
      run: dotnet build Cloudflare.NET.sln --no-restore

    - name: Run Fast Tests (Unit) on Pull Requests
      # This step runs on every pull request for quick feedback.
      # It explicitly EXCLUDES the 'Integration' category, so no live API calls are made.
      # It does not require secrets to succeed.
      if: github.event_name == 'pull_request'
      run: dotnet test Cloudflare.NET.sln --no-build --verbosity normal --filter "TestCategory!=Integration"

    - name: Run All Tests on Main Branch (Unit and Integration)
      # This step ONLY runs after a merge to the 'main' branch.
      # It runs the full test suite, including live integration tests.
      # This step REQUIRES the secrets to be configured in the repository.
      if: github.event_name != 'pull_request'
      run: dotnet test Cloudflare.NET.sln --no-build --verbosity normal
      env:
        # These secrets must be configured in the GitHub repository settings.
        # The double underscore `__` is the standard convention for mapping
        # environment variables to nested JSON configuration keys.
        Cloudflare__ApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        Cloudflare__AccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        Cloudflare__ZoneId: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        Cloudflare__BaseDomain: ${{ secrets.CLOUDFLARE_BASE_DOMAIN }}